DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS webhook_subscriptions CASCADE;
DROP TABLE IF EXISTS skills CASCADE;
DROP TABLE IF EXISTS models CASCADE;
DROP TABLE IF EXISTS model_providers CASCADE;
